/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mPM8snqjebu
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card, CardFooter } from "@/components/ui/card"

export function products() {
  return (
    (<div className="bg-[#FFF3E4] p-6">
      <h1 className="text-4xl font-bold text-orange-600">Sweet surprises</h1>
      <p className="mt-2 text-lg">From baskets to treats, find all you need to celebrate this spring.</p>
      <Button className="mt-4 bg-orange-500 text-white">Everything Easter</Button>
      <div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-4">
        <Card className="bg-white">
          <img
            alt="Styles for all"
            className="h-36 w-full object-cover"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <CardContent>
            <p className="text-sm">Styles for all</p>
            <p className="text-xs text-gray-500">Dressy spring looks for Easter & beyond.</p>
          </CardContent>
        </Card>
        <Card className="bg-white">
          <img
            alt="Baskets"
            className="h-36 w-full object-cover"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <CardContent>
            <p className="text-sm">From $3</p>
            <p className="text-xs text-gray-500">Baskets</p>
          </CardContent>
        </Card>
        <Card className="bg-white">
          <img
            alt="Candy"
            className="h-36 w-full object-cover"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <CardContent>
            <p className="text-sm">Under $5</p>
            <p className="text-xs text-gray-500">Candy</p>
          </CardContent>
        </Card>
        <Card className="bg-white">
          <img
            alt="Cool gifts for kiddos"
            className="h-36 w-full object-cover"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <CardContent>
            <p className="text-sm">Cool gifts for kiddos</p>
            <p className="text-xs text-gray-500">Make their day with spring sweets & fun playtime finds.</p>
          </CardContent>
        </Card>
      </div>
      <h2 className="mt-8 mb-4 text-2xl font-semibold">Best-selling Easter Toys</h2>
      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <Card className="bg-white">
          <img
            alt="Bubble Wands"
            className="h-36 w-full object-cover"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <CardContent>
            <p className="text-sm font-bold">$5.00</p>
            <p className="text-xs">6pk 4oz Bubble Wands - Sun Squad™</p>
          </CardContent>
          <CardFooter className="flex justify-center">
            <Button>Add to cart</Button>
          </CardFooter>
        </Card>
        <Card className="bg-white">
          <img
            alt="LEGO Creator Easter Bunny"
            className="h-36 w-full object-cover"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <CardContent>
            <p className="text-sm font-bold">$4.99</p>
            <p className="text-xs">LEGO Creator Easter Bunny with Colorful...</p>
          </CardContent>
          <CardFooter className="flex justify-center">
            <Button>Add to cart</Button>
          </CardFooter>
        </Card>
        <Card className="bg-white">
          <img
            alt="Bubble Solution"
            className="h-36 w-full object-cover"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <CardContent>
            <p className="text-sm font-bold">$1.00</p>
            <p className="text-xs">Bubble Solution 16oz - Sun Squad™</p>
          </CardContent>
          <CardFooter className="flex justify-center">
            <Button>Add to cart</Button>
          </CardFooter>
        </Card>
        <Card className="bg-white">
          <img
            alt="LEGO Cherry Blossoms"
            className="h-36 w-full object-cover"
            height="150"
            src="/placeholder.svg"
            style={{
              aspectRatio: "150/150",
              objectFit: "cover",
            }}
            width="150" />
          <CardContent>
            <p className="text-sm font-bold">$14.99</p>
            <p className="text-xs">LEGO Cherry Blossoms Celebrato...</p>
          </CardContent>
          <CardFooter className="flex justify-center">
            <Button>Add to cart</Button>
          </CardFooter>
        </Card>
      </div>
    </div>)
  );
}
