/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vEyp7DmCdjt
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { PaginationPrevious, PaginationItem, PaginationLink, PaginationEllipsis, PaginationNext, PaginationContent, Pagination } from "@/components/ui/pagination"

export function productCard() {
  return (
    (<div className="min-h-screen bg-gray-100 dark:bg-gray-900">
      <header className="bg-white dark:bg-gray-800 shadow-sm py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#">
            <a className="text-2xl font-bold text-gray-900 dark:text-gray-100" href="#">
              NextTarget
            </a>
          </Link>
          <form className="relative w-full max-w-md">
            <input
              className="w-full rounded-md pl-10 pr-4 py-2 border border-gray-200 border-gray-300 dark:border-gray-700 focus:border-blue-500 focus:outline-none dark:bg-gray-800 dark:text-gray-100 dark:border-gray-800"
              placeholder="Search products..."
              type="text" />
            <SearchIcon
              className="absolute left-3 top-1/2 transform -translate-y-1/2 h-6 w-6 text-gray-500 dark:text-gray-400" />
          </form>
        </div>
      </header>
      <main className="container mx-auto py-6 px-4">
        <div
          className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          <div className="group">
            <div
              className="w-full h-64 overflow-hidden rounded-lg shadow-md bg-white dark:bg-gray-800">
              <img
                alt="Product Image"
                className="w-full h-full object-cover transform group-hover:scale-105 transition-transform"
                height={500}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "500/500",
                  objectFit: "cover",
                }}
                width={500} />
            </div>
            <div className="py-2 px-3">
              <h3 className="text-gray-700 dark:text-gray-100 text-sm font-medium">Product Title</h3>
              <p className="mt-1 text-lg font-semibold text-gray-900 dark:text-gray-100">$49.99</p>
            </div>
            <Button className="w-full mt-2">Add to Cart</Button>
          </div>
        </div>
        <div className="flex items-center justify-center mt-6">
          <Pagination>
            <PaginationContent>
              <PaginationItem>
                <PaginationPrevious href="#" />
              </PaginationItem>
              <PaginationItem>
                <PaginationLink href="#">1</PaginationLink>
              </PaginationItem>
              <PaginationItem>
                <PaginationLink href="#" isActive>
                  2
                </PaginationLink>
              </PaginationItem>
              <PaginationItem>
                <PaginationLink href="#">3</PaginationLink>
              </PaginationItem>
              <PaginationItem>
                <PaginationEllipsis />
              </PaginationItem>
              <PaginationItem>
                <PaginationNext href="#" />
              </PaginationItem>
            </PaginationContent>
          </Pagination>
        </div>
      </main>
    </div>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
